In [11]:
import pandas as pd

In [12]:
qualifying_df = pd.read_csv("qualifying.csv",index_col=False)
qualifying_df

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236
...,...,...,...,...,...,...,...,...,...
9250,9308,1079,20,117,5,16,1:20.954,\N,\N
9251,9309,1079,4,214,14,17,1:21.043,\N,\N
9252,9310,1079,840,117,18,18,1:21.418,\N,\N
9253,9311,1079,848,3,23,19,1:21.645,\N,\N
9254,9312,1079,849,3,6,20,1:21.915,\N,\N

In [14]:
drivers_df = pd.read_csv("drivers.csv",index_col=False)
drivers_df

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
849,851,aitken,89,AIT,Jack,Aitken,1995-09-23,British,http://en.wikipedia.org/wiki/Jack_Aitken
850,852,tsunoda,22,TSU,Yuki,Tsunoda,2000-05-11,Japanese,http://en.wikipedia.org/wiki/Yuki_Tsunoda
851,853,mazepin,9,MAZ,Nikita,Mazepin,1999-03-02,Russian,http://en.wikipedia.org/wiki/Nikita_Mazepin
852,854,mick_schumacher,47,MSC,Mick,Schumacher,1999-03-22,German,http://en.wikipedia.org/wiki/Mick_Schumacher
853,855,zhou,24,ZHO,Guanyu,Zhou,1999-05-30,Chinese,http://en.wikipedia.org/wiki/Guanyu_Zhou

In [16]:
driver_standings_df = pd.read_csv("driver_standings.csv",index_col=False)
driver_standings_df

,driverStandingsId,raceId,driverId,points,position,positionText,wins
0,1,18,1,10.0,1,1,1
1,2,18,2,8.0,2,2,0
2,3,18,3,6.0,3,3,0
3,4,18,4,5.0,4,4,0
4,5,18,5,4.0,5,5,0
...,...,...,...,...,...,...,...
33534,71371,1079,807,0.0,20,20,0
33535,71372,1079,815,85.0,3,3,0
33536,71373,1079,830,110.0,1,1,4
33537,71374,1079,842,6.0,13,13,0
33538,71375,1079,20,4.0,14,14,0

In [17]:
races_df = pd.read_csv("races.csv",index_col=False)
races_df

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1074,1092,2022,18,22,Japanese Grand Prix,2022-10-09,05:00:00,http://en.wikipedia.org/wiki/2022_Japanese_Gra...,2022-10-07,04:00:00,2022-10-07,08:00:00,2022-10-08,04:00:00,2022-10-08,07:00:00,\N,\N
1075,1093,2022,19,69,United States Grand Prix,2022-10-23,19:00:00,http://en.wikipedia.org/wiki/2022_United_State...,2022-10-21,19:00:00,2022-10-21,22:00:00,2022-10-22,19:00:00,2022-10-22,22:00:00,\N,\N
1076,1094,2022,20,32,Mexico City Grand Prix,2022-10-30,20:00:00,http://en.wikipedia.org/wiki/2022_Mexican_Gran...,2022-10-28,18:00:00,2022-10-28,21:00:00,2022-10-29,17:00:00,2022-10-29,20:00:00,\N,\N
1077,1095,2022,21,18,Brazilian Grand Prix,2022-11-13,18:00:00,http://en.wikipedia.org/wiki/2022_Brazilian_Gr...,2022-11-11,15:30:00,2022-11-12,15:30:00,\N,\N,2022-11-11,19:00:00,2022-11-12,19:30:00
1078,1096,2022,22,24,Abu Dhabi Grand Prix,2022-11-20,13:00:00,http://en.wikipedia.org/wiki/2022_Abu_Dhabi_Gr...,2022-11-18,09:00:00,2022-11-18,12:00:00,2022-11-19,10:00:00,2022-11-19,13:00:00,\N,\N

In [18]:
results_df = pd.read_csv("results.csv",index_col=False)
results_df

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25515,25521,1079,849,3,6,19,16,16,16,0.0,64,\N,\N,52,14,1:27.246,192.902,12
25516,25522,1079,825,210,20,8,17,17,17,0.0,64,\N,\N,3,17,1:27.537,192.261,12
25517,25523,1079,848,3,23,18,18,18,18,0.0,64,\N,\N,56,19,1:28.281,190.641,12
25518,25524,1079,855,51,24,15,\N,R,19,0.0,28,\N,\N,12,20,1:28.415,190.352,131
25519,25525,1079,844,6,16,1,\N,R,20,0.0,27,\N,\N,25,13,1:27.030,193.381,131

In [20]:
#Machine Learning: Logistic Regression um Probability des WM-Titels fÃ¼r jeden Fahrer vorherzusagen. --> DRIVER mit hÃ¶chster Prob wird gemÃ¤ss Modell WM Sieger.
#--> Inputfaktoren: Gewichtete Parameter (siehe unten 1-6)
# y-Achse = Probability (0-1) / x-Achse = weighted sum of input features (Gewichtete Parameter, x1 + x2 etc.)
#Welche Daten sind fÃ¼r die Prediction relevant? 
# 1) Starting Grid Position --> QF RÃ¤nge Durchschnitt pro Saison 
# 2) Alter (Erfahrung als Fahrer vs. irgendwann Peak erreicht und zu alt)
# 3) Fahrzeuge / Teams gewichten (z.B: RedBull hÃ¶here Wahrscheinlichkeit als Williams)
# 4) Budget (Welcher Constructor hat wie viel Geld? --> Viel Geld hÃ¶here Chance als wenig. Geld)
# 5) Marktwert Driver 
# 6) Hype auf social Media (Einfluss Anzahl Tweets pro Team pro Wochenende oder Season auf Schlussrangierung WM-Klassement)
# 7) Aktuelle Rangposition des DRIVERs --> aktuell beim Live Modell
# 8) WM Klassierung vergangene Jahre 
# AbhÃ¤ngige Variabel: Probability of Chance to Win the Championship pro DRRIVER 

#Wie werden die Parameter gewichtet? --> Analyse der letzen x Jahre auf Auswirkung der Parameter auf WM Titel.
# Wie werden die Daten ins Modell eingebaut --> Features erstellen x1, x2, etc. / Parameter. sind immer in AbhÃ¤ngigkeit 
#zum Ergebnis der Rangliste der einzelnen Rennen
# Gewichtung der Parameter werden auf Basis von historischen Daten gemacht --> 2016 - 2021
# Steps: 
# 1)Basisdataset erstellen --> CSV / Cleansing (bsp. Tabelle --> Name Driver, Rennergebnisse, Starting Grid, Alter Fahrer, Jahres Budget Team, Marktwert Driver, Aktuelle Rangposition des Drivers.  )
# 2)Features erstellen aus Dataset --> x1, x2, x3, 
# 3)Sklearn Logistic Regression Model einsetzen mit Features --> Trainings Daten 2016 - 2020 / Test 2021 / Live: aktuelle Daten
# 4)Docker Instanz
# 5)API checken
# 6)Verbdindung Model Prediction mit Scraping --> If Driver with highest Probability = Verstappen then print Picture of Verstappen
# 7)Bias und kritische WÃ¼rdigung
# 8)PrÃ¤sentation erstellen 
# 9)Video aufnehmen